### ISSUE TITLE
Getting issue in installing the extension

### ISSUE THREAD

**Issue by allinvinod** [php-cuong/magento2-city-dropdown#1]
I am run below command:

> **composer require php-cuong/magento2-city-dropdown**

Getting error message:

**[InvalidArgumentException]
  Could not find a version of package php-cuong/magento2-city-dropdown matching your minimum-stability (alpha). Require it with an explicit version constraint allowing its desired stability.**

**Comment by php-cuong** [comment]
You can use my extension with Magento 2.1.x, 2.2.x and 2.3.x. The price is $145 for this extension. I accept the Western Union payment method. Please contact me on skype: cuongnq87 or facebook: https://www.facebook.com/giaphugroupcom/
