### ISSUE TITLE
Is it paid extension ?

### ISSUE THREAD

**Issue by rustsol** [php-cuong/magento2-city-dropdown#2]
Is this paid extension, i don't see you mentioned code anywhere?

**Comment by php-cuong** [comment]
Yeah! You can see the demo here https://www.youtube.com/watch?v=ugZXjsNKM0w&index=6&list=PL98CDCbI3TNslCicN4cJyR4_hBXR1clhW

**Comment by php-cuong** [comment]
You can use my extension with Magento 2.1.x, 2.2.x and 2.3.x. The price is $145 for this extension. I accept the Western Union payment method. Please contact me on skype: cuongnq87 or facebook: https://www.facebook.com/giaphugroupcom/
