### ISSUE TITLE
Magento 2.3.2

### ISSUE THREAD

**Issue by LucianMihalache** [php-cuong/magento2-city-dropdown#3]
Hi, is the extension compatible with 2.3.2?
And how much does it cost? I don't see any price

**Comment by php-cuong** [comment]
Yes! You can use my extension with Magento 2.1.x, 2.2.x and 2.3.x. The price is $145 for this extension. I accept the Western Union payment method. Please contact me on skype: cuongnq87 or facebook: https://www.facebook.com/giaphugroupcom/
